config/routes.rb
Rails.application.routes.draw do
  root 'trips#index'

  resources :trips do
    resources :locations
  end
  
  resources :locations do
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :location
  validates :street, :city, :state, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip
  has_one :address, dependent: :destroy
  validates :name, :days, presence: true
end

app/models/trip.rb
class Trip < ApplicationRecord
  validates :name, :start_date, :end_date, presence: true
  has_many :locations, dependent: :destroy
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_location
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  def index
    @addresses = Address.all
  end

  def show
  end

  def new
    @address = @location.addresses.new
  #  render partial: 'form'
  end

  def create
    @address = @location.addresses.new(address_params)
    if @address.save
      redirect_to [@location, @address]
    else
      render :new
    end
  end

  def edit
 #   render partial: 'form'
  end

  def update
    if @address.update(address_params)
      redirect_to [@location, @address]
    else
      render :edit
    end
  end

  def destroy
    @address.destroy
    redirect_to location_addresses_path(@location)
  end

  private
    def address_params
      params.require(:address).permit(:street, :city, :state, :zip)
    end

  def set_address
    @address = Address.find(params[:id])
  end

  def set_location
    @location = Location.find(params[:location_id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :set_trip

  def index
    @locations = @trip.locations
  end

  def show
  end

  def new
    @location = @trip.locations.new
    # render partial: "form"
  end

  def create
    @location = @trip.locations.new(location_params)
    if @location.save
      redirect_to [@trip, @location]
    else
      render :new
    end
  end

  def edit
    # render partial: "form"
  end

  def update
    if @location.update(location_params)
      redirect_to [@trip, @location]
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to trip_locations_path(@trip)
  end

  private
    def location_params
      params.require(:location).permit(:name, :days)
    end

    def set_location
      @location = Location.find(params[:id])
    end

    def set_trip
      @trip = Trip.find(params[:trip_id])
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # before_action :set_trip, only: [:show, :edit, :destroy, :update]

  def index
    @trips = Trip.all        
  end

  def show
    @trip = Trip.find(params[:id])
    # render show.html.erb
  end

  def new
    @trip = Trip.new
    #render partial: 'form'
    # render new.html.erb
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      redirect_to trips_path
    else
      render :new
    end
  end

  def edit
    @trip = Trip.find(params[:id])
    #render partial: 'form'

  end

  def update    #look up a particular record and return the record
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to trips_path
    else
      render :edit
    end
  end

  def destroy
    # @sub = Sub.find(params[:id])
    # @sub.destroy
    # redirect_to subs_path

    Trip.find(params[:id]).destroy
    redirect_to trips_path
  end

  private
   def trip_params
    params.require(:trip).permit(:name, :start_date, :end_date)
   end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/_form.html.erb
<h1>Add Address</h1>

<%= form_for @address do |f| %>
  <%= f.label :street %>
  <%= f.text_field :street, required: true, placeholder: 'Street' %>
  <%= f.label :city %>
  <%= f.text_field :city, required: true, placeholder: 'City' %>
  <%= f.label :state %>
  <%= f.text_field :state, required: true, placeholder: 'State' %>
  <%= f.label :zip %>
  <%= f.text_field :zip, required: true, placeholder: 'Zip Code' %>


  <%= f.submit nil, class: 'ui blue button' %>
<% end %>

app/views/addresses/edit.html.erb
<h1>Edit Address</h1>

<%= form_with(model: [@location, @address], local: true, class: 'ui form') do |f| %>
  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street, required: true, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city, required: true %>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state, required: true %>
  </div>
  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip, required: true %>
  </div>

  <%= f.submit nil, class: 'ui green button' %>
<% end %>

app/views/addresses/index.html.erb
<h1>Addresses</h1>

<% @addresses.each do |address| %>

  <%= link_to address.location, [@location, @address] %>
<% end %>




<h1><%= @trip.name %> Trip Stops</h1>
 <ul>
  <% @locations.each do |location| %>
    <li>
      <%= link_to location.name, [ @trip, location ]%>
    </li>
    <% end %>
 </ul>

 <%= link_to 'Create new location', new_trip_location_path(@trip) %>

app/views/addresses/new.html.erb
<h1>Add Address</h1>

<hr/>
<%= form_with(model: [@location, @address], local: true, class: 'ui form') do |f| %>
  
  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street, required: true, autofocus: true %>
  </div>
  
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city, required: true, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state, required: true, autofocus: true %>
  </div> 

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip, required: true, autofocus: true %>
  </div> 

  <%= f.submit nil, class: 'ui green button' %>
<% end %>

app/views/addresses/show.html.erb
<h1><%= @address.street %></h1>


<%= link_to 'Edit Address', edit_location_address_path([@location, @address]) %>
<br/>
<%= link_to 'Delete Address', [@location, @address], method: :delete %>
<br/>
<%= link_to 'Back to Location', trip_location_path(@trip, @location) %>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Trips', trips_path %>
    </li>
    <li>
      <%= link_to 'Add Trip', new_trip_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roadtrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class='ui container'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<h1>Add Location</h1>
<hr />
<%= form_for [@trip, @location] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, placeholder: 'Trip Location' %>
  <%= f.label :days %>
  <%= f.text_field :days, required: true, placeholder: 'Days' %>

  <%= f.submit nil, class: 'ui blue button' %>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>

<%= form_with(model: [@trip, @location], local: true, class: 'ui form') do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :days %>
    <%= f.text_field :days, required: true %>
  </div>

  <%= f.submit nil, class: 'ui green button' %>
<% end %>

app/views/locations/index.html.erb
<h1><%= @trip.name %> Trip Stops</h1>
 <ul>
  <% @locations.each do |location| %>
    <li>
      <%= link_to location.name, [ @trip, location ]%>
    </li>
    <% end %>
 </ul>

 <%= link_to 'Create new location', new_trip_location_path(@trip) %>

app/views/locations/new.html.erb
<h1>Add Location</h1>
<hr/>
<%= form_with(model: [@trip, @location], local: true, class: 'ui form') do |f| %>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
  </div>
  
  <div class="field">
    <%= f.label :days %>
    <%= f.text_field :days, required: true, autofocus: true %>
  </div>


  <%= f.submit nil, class: 'ui green button' %>
<% end %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>
<p><%= @location.days %> Day Stop</p>
<%= @location.address.street %>
<%= @location.address.city %>
<br/>
<%= @location.address.state %>
<br/>
<%= @location.address.zip %>
 
<br/>
<br/>

<%= link_to 'Edit Location', edit_trip_location_path([@trip, @location]) %>
<br/>
<%= link_to 'Delete Location', [@trip, @location], method: :delete %>
<br/>
<%= link_to 'Back to Location', trip_location_path(@trip) %>
<br />
<%= link_to 'Edit Address', edit_location_address_path(@location) %>

app/views/trips/_form.html.erb
<h1>Add Trip</h1>

<%= form_for @trip do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, placeholder: 'Trip Location' %>
  <%= f.label :start_date %>
  <%= f.text_field :start_date, required: true, placeholder: 'Start Date' %>
  <%= f.label :end_date %>
  <%= f.text_field :end_date, required: true, placeholder: 'End Date' %>


  <%= f.submit nil, class: 'ui blue button' %>
<% end %>

app/views/trips/edit.html.erb
<h1>Trips</h1>

<%= form_with(model: @trip, local: true, class: 'ui form') do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :start_date %>
    <%= f.text_field :start_date, required: true %>
  </div>
  <div class="field">
    <%= f.label :end_date %>
    <%= f.text_field :end_date, required: true %>
  </div>

  <%= f.submit nil, class: 'ui green button' %>
<% end %>

app/views/trips/index.html.erb
<h1>All Trips</h1>

<ul>
  <% @trips.each do |trip| %>
    <li>
      <%= link_to trip.name, trip %>
    </li>
    <% end %>
</ul>

app/views/trips/new.html.erb
<h1>Add Trip</h1>
<hr/>
<%= form_with(model: @trip, local: true, class: 'ui form') do |f| %>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
  </div>
  
  <div class="field">
    <%= f.label :start_date %>
    <%= f.text_field :start_date, required: true, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.text_field :end_date, required: true %>
  </div>

  <%= f.submit nil, class: 'ui green button' %>
<% end %>

app/views/trips/show.html.erb
<h1><%= @trip.name %></h1>
<hr />
<p>Where would you like to go?</p>

<%= link_to 'View all Trips', trips_path %>
<br />
<%= link_to 'View Locations', trip_locations_path(@trip) %>
<br />
<%= link_to 'Edit Trip', edit_trip_path(@trip) %>
<br />
<%= link_to 'Delete Trip', @trip, method: :delete %>